Naming a vector

In [2]:
poker_vector <- c(140, -50, 20, -120, 240)

roulette_vector <- c(-24, -50, 100, -350, 10)

In [3]:
names(poker_vector) <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")

In [4]:
poker_vector

Monday   Tuesday Wednesday  Thursday    Friday 
      140       -50        20      -120       240

In [5]:
names(roulette_vector) <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")

In [6]:
roulette_vector

Monday   Tuesday Wednesday  Thursday    Friday 
      -24       -50       100      -350        10

## 3 ways of creating named vectors

In [7]:
named_vector <- c(A = 12, B = 13, C = 15)

In [8]:
named_vector

A  B  C 
12 13 15

In [9]:
named_vector_1 = setNames(c(1,2,3), c("A","B","C"))

In [10]:
named_vector_1

A B C 
1 2 3

In [12]:
v <- c(1,2,3)

In [13]:
names(v) <- c("name 1", "name 2", "name 3")

In [14]:
v

name 1 name 2 name 3 
     1      2      3

In [15]:
## practice

a <- c(A = 1, B = 12, C = 43)

In [16]:
a

A  B  C 
 1 12 43

In [17]:
b <- setNames(c(10,11,12),c("a","b","c"))

In [18]:
b

a  b  c 
10 11 12

In [19]:
c <- 10:12

In [20]:
names(c) <- c("m", "n", "o")

In [21]:
c

m  n  o 
10 11 12

In [22]:
sum(c)

[1] 33

# Indexing Vectors

**Logical Vectors**

In [37]:
x <- 1:10

In [24]:
x[x %% 2 == 0]

[1]  2  4  6  8 10

In [25]:
x[x %% 2 != 0]

[1] 1 3 5 7 9

In [38]:
x[x > 5]

[1]  6  7  8  9 10

**Vector of positive integral quantities**

In [27]:
x <- 90 : 100

In [28]:
x

[1]  90  91  92  93  94  95  96  97  98  99 100

In [29]:
x[c(1,3,5)]

[1] 90 92 94

**Vector of negative integral quantities**

In [32]:
x[-c(2,4,6,7,8,9,10,11)]

[1] 90 92 94

**Vector of character strings**

In [34]:
x <- c(A = 23, B = 12, C = 55, D = 12, E = 99, F = 67)

In [35]:
x

A  B  C  D  E  F 
23 12 55 12 99 67

In [36]:
x[c("A","B","F")]

A  B  F 
23 12 67

# Matrices

In [39]:
matrix(1:9)

[,1]
 [1,] 1   
 [2,] 2   
 [3,] 3   
 [4,] 4   
 [5,] 5   
 [6,] 6   
 [7,] 7   
 [8,] 8   
 [9,] 9

In [40]:
matrix(1:9, nrow = 3)

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [41]:
matrix(1:9, nrow = 3, byrow = T)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [43]:
mdat <- matrix(c(1,2,3, 11,12,13), nrow = 2, ncol = 3, byrow = TRUE,
               dimnames = list(c("row1", "row2"),
                               c("C.1", "C.2", "C.3")))

In [44]:
mdat

C.1 C.2 C.3
row1  1   2   3 
row2 11  12  13

In [45]:
new_hope <- c(460.998, 314.4)

empire_strikes <- c(290.475, 247.900)

return_jedi <- c(309.306, 165.8)

In [46]:
box_office <- c(new_hope, empire_strikes, return_jedi)

In [47]:
box_office

[1] 460.998 314.400 290.475 247.900 309.306 165.800

In [54]:
(star_wars_matrix <- matrix(box_office, nrow = 3, byrow = T))

[,1]    [,2] 
[1,] 460.998 314.4
[2,] 290.475 247.9
[3,] 309.306 165.8

In [55]:
dimnames(star_wars_matrix) <- list(c("A","B","C"))

In [56]:
star_wars_matrix

[,1]    [,2] 
A 460.998 314.4
B 290.475 247.9
C 309.306 165.8

In [57]:
ab <- matrix(10:15, nrow = 2)

In [58]:
ab

[,1] [,2] [,3]
[1,] 10   12   14  
[2,] 11   13   15

In [59]:
rownames(ab) <- c("row 1", "row 2")

In [60]:
ab

[,1] [,2] [,3]
row 1 10   12   14  
row 2 11   13   15

In [61]:
colnames(ab) <- c("col 1", "col 2", "col 3")

In [62]:
ab

col 1 col 2 col 3
row 1 10    12    14   
row 2 11    13    15

In [63]:
region <- c("US", "non-US")
titles <- c("A New Hope", "The Empire Strikes Back", "Return of the Jedi")

In [64]:
rownames(star_wars_matrix) <- titles

In [65]:
colnames(star_wars_matrix) <- region

In [66]:
star_wars_matrix

US      non-US
A New Hope              460.998 314.4 
The Empire Strikes Back 290.475 247.9 
Return of the Jedi      309.306 165.8

In [67]:
rowSums(ab)

row 1 row 2 
   36    39

In [68]:
rowSums(star_wars_matrix)

A New Hope The Empire Strikes Back      Return of the Jedi 
                775.398                 538.375                 475.106

In [69]:
box_office <- c(460.998, 314.4, 290.475, 247.900, 309.306, 165.8)
star_wars_matrix <- matrix(box_office, nrow = 3, byrow = TRUE,
                           dimnames = list(c("A New Hope", "The Empire Strikes Back", "Return of the Jedi"), 
                                           c("US", "non-US")))

# The worldwide box office figures
worldwide_vector <- rowSums(star_wars_matrix)

# Bind the new variable worldwide_vector as a column to star_wars_matrix
all_wars_matrix <- cbind(star_wars_matrix, worldwide_vector)

In [70]:
all_wars_matrix

US      non-US worldwide_vector
A New Hope              460.998 314.4  775.398         
The Empire Strikes Back 290.475 247.9  538.375         
Return of the Jedi      309.306 165.8  475.106

In [71]:
colSums(all_wars_matrix)

US           non-US worldwide_vector 
        1060.779          728.100         1788.879

## Selection of matrix elements

In [73]:
data <- c(461.0, 314.4, 290.5, 247.9, 309.3, 165.8, 474.5, 552.5, 310.7, 338.7 ,380.3, 468.5)

In [76]:
all_wars_matrix <- matrix(data, ncol = 2, byrow = T)

In [77]:
all_wars_matrix

[,1]  [,2] 
[1,] 461.0 314.4
[2,] 290.5 247.9
[3,] 309.3 165.8
[4,] 474.5 552.5
[5,] 310.7 338.7
[6,] 380.3 468.5

In [78]:
rownames(all_wars_matrix) <- c("A New Hope", "The Empire Strikes Back", "Return of the Jedi",
                              "The Phantom Menace", "Attack of the Clones", "Revenge of the Sith")

In [79]:
all_wars_matrix

[,1]  [,2] 
A New Hope              461.0 314.4
The Empire Strikes Back 290.5 247.9
Return of the Jedi      309.3 165.8
The Phantom Menace      474.5 552.5
Attack of the Clones    310.7 338.7
Revenge of the Sith     380.3 468.5

In [80]:
colnames(all_wars_matrix) <- c("US", "non-US") 

In [81]:
all_wars_matrix

US    non-US
A New Hope              461.0 314.4 
The Empire Strikes Back 290.5 247.9 
Return of the Jedi      309.3 165.8 
The Phantom Menace      474.5 552.5 
Attack of the Clones    310.7 338.7 
Revenge of the Sith     380.3 468.5

In [83]:
## non-US revenues for all movies

all_wars_matrix[, 2]

A New Hope The Empire Strikes Back      Return of the Jedi 
                  314.4                   247.9                   165.8 
     The Phantom Menace    Attack of the Clones     Revenge of the Sith 
                  552.5                   338.7                   468.5

In [84]:
mean(all_wars_matrix[, 2])

[1] 347.9667

In [85]:
all_wars_matrix[ c(1,2), 2]

A New Hope The Empire Strikes Back 
                  314.4                   247.9

In [86]:
mean(all_wars_matrix[ c(1,2), 2])

[1] 281.15

In [88]:
all_wars_matrix / 5

US    non-US
A New Hope              92.20  62.88
The Empire Strikes Back 58.10  49.58
Return of the Jedi      61.86  33.16
The Phantom Menace      94.90 110.50
Attack of the Clones    62.14  67.74
Revenge of the Sith     76.06  93.70

# Factors

*factors = categorical variables*

In [89]:
sex_vector <- c("Male", "Female", "Female", "Male", "Male")

In [90]:
factor_sex_vector <- factor(sex_vector)

In [91]:
factor_sex_vector

[1] Male   Female Female Male   Male  
Levels: Female Male

There are two types of categorical variables: nominal, ordinal

In [92]:
temperature_vector <- c("High", "Low", "High","Low", "Medium")
factor_temperature_vector <- factor(temperature_vector, order = TRUE, levels = c("Low", "Medium", "High"))
factor_temperature_vector

[1] High   Low    High   Low    Medium
Levels: Low < Medium < High

In [93]:
survey_vector <- c("M", "F", "F", "M", "M")
factor_survey_vector <- factor(survey_vector)

# Specify the levels of factor_survey_vector
levels(factor_survey_vector) <- c("Female", "Male")

factor_survey_vector

[1] Male   Female Female Male   Male  
Levels: Female Male

In [94]:
summary(factor_survey_vector)

Female   Male 
     2      3

In [95]:
speed_vector <- c("medium", "slow", "slow", "medium", "fast")

In [96]:
speed_factor <- factor(speed_vector, ordered = T, levels = c("slow", "medium", "fast"))

In [97]:
summary(speed_factor)

slow medium   fast 
     2      2      1

In [98]:
# Create factor_speed_vector
speed_vector <- c("medium", "slow", "slow", "medium", "fast")
factor_speed_vector <- factor(speed_vector, ordered = TRUE, levels = c("slow", "medium", "fast"))

# Factor value for second data analyst
da2 <- factor_speed_vector[2]

# Factor value for fifth data analyst
da5 <- factor_speed_vector[5]

# Is data analyst 2 faster than data analyst 5?
da2 > da5

[1] FALSE

In [99]:
mtcars

mpg  cyl disp  hp  drat wt    qsec  vs am gear carb
Mazda RX4           21.0 6   160.0 110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag       21.0 6   160.0 110 3.90 2.875 17.02 0  1  4    4   
Datsun 710          22.8 4   108.0  93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive      21.4 6   258.0 110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout   18.7 8   360.0 175 3.15 3.440 17.02 0  0  3    2   
Valiant             18.1 6   225.0 105 2.76 3.460 20.22 1  0  3    1   
Duster 360          14.3 8   360.0 245 3.21 3.570 15.84 0  0  3    4   
Merc 240D           24.4 4   146.7  62 3.69 3.190 20.00 1  0  4    2   
Merc 230            22.8 4   140.8  95 3.92 3.150 22.90 1  0  4    2   
Merc 280            19.2 6   167.6 123 3.92 3.440 18.30 1  0  4    4   
Merc 280C           17.8 6   167.6 123 3.92 3.440 18.90 1  0  4    4   
Merc 450SE          16.4 8   275.8 180 3.07 4.070 17.40 0  0  3    3   
Merc 450SL          17.3 8   275.8 180 3.07 3.730 17.60 0  0  3    3   
Merc 450SLC         15.2 8   275.8 180 3.07 3.780 18.00 0  0  3    3   
Cadillac Fleetwood  10.4 8   472.0 205 2.93 5.250 17.98 0  0  3    4   
Lincoln Continental 10.4 8   460.0 215 3.00 5.424 17.82 0  0  3    4   
Chrysler Imperial   14.7 8   440.0 230 3.23 5.345 17.42 0  0  3    4   
Fiat 128            32.4 4    78.7  66 4.08 2.200 19.47 1  1  4    1   
Honda Civic         30.4 4    75.7  52 4.93 1.615 18.52 1  1  4    2   
Toyota Corolla      33.9 4    71.1  65 4.22 1.835 19.90 1  1  4    1   
Toyota Corona       21.5 4   120.1  97 3.70 2.465 20.01 1  0  3    1   
Dodge Challenger    15.5 8   318.0 150 2.76 3.520 16.87 0  0  3    2   
AMC Javelin         15.2 8   304.0 150 3.15 3.435 17.30 0  0  3    2   
Camaro Z28          13.3 8   350.0 245 3.73 3.840 15.41 0  0  3    4   
Pontiac Firebird    19.2 8   400.0 175 3.08 3.845 17.05 0  0  3    2   
Fiat X1-9           27.3 4    79.0  66 4.08 1.935 18.90 1  1  4    1   
Porsche 914-2       26.0 4   120.3  91 4.43 2.140 16.70 0  1  5    2   
Lotus Europa        30.4 4    95.1 113 3.77 1.513 16.90 1  1  5    2   
Ford Pantera L      15.8 8   351.0 264 4.22 3.170 14.50 0  1  5    4   
Ferrari Dino        19.7 6   145.0 175 3.62 2.770 15.50 0  1  5    6   
Maserati Bora       15.0 8   301.0 335 3.54 3.570 14.60 0  1  5    8   
Volvo 142E          21.4 4   121.0 109 4.11 2.780 18.60 1  1  4    2

In [101]:
str(mtcars)

'data.frame':	32 obs. of  11 variables:
 $ mpg : num  21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
 $ cyl : num  6 6 4 6 8 6 8 4 4 6 ...
 $ disp: num  160 160 108 258 360 ...
 $ hp  : num  110 110 93 110 175 105 245 62 95 123 ...
 $ drat: num  3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92 ...
 $ wt  : num  2.62 2.88 2.32 3.21 3.44 ...
 $ qsec: num  16.5 17 18.6 19.4 17 ...
 $ vs  : num  0 0 1 1 0 1 0 1 1 1 ...
 $ am  : num  1 1 1 0 0 0 0 0 0 0 ...
 $ gear: num  4 4 4 3 3 3 3 4 4 4 ...
 $ carb: num  4 4 1 1 2 1 4 2 2 4 ...


In [102]:
head(mtcars)

mpg  cyl disp hp  drat wt    qsec  vs am gear carb
Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1  4    4   
Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1  4    4   
Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1  4    1   
Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0  3    1   
Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0  3    2   
Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0  3    1

In [103]:
## creating a dataframe

name <- c("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")

type <- c("Terrestrial planet", "Terrestrial planet", "Terrestrial planet", 
          "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant")

diameter <- c(0.382, 0.949, 1, 0.532, 11.209, 9.449, 4.007, 3.883)

rotation <- c(58.64, -243.02, 1, 1.03, 0.41, 0.43, -0.72, 0.67)

rings <- c(FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE)

In [104]:
planets_df <- data.frame(name, type, diameter, rotation, rings)

In [105]:
head(planets_df)

name    type               diameter rotation rings
1 Mercury Terrestrial planet  0.382     58.64  FALSE
2 Venus   Terrestrial planet  0.949   -243.02  FALSE
3 Earth   Terrestrial planet  1.000      1.00  FALSE
4 Mars    Terrestrial planet  0.532      1.03  FALSE
5 Jupiter Gas giant          11.209      0.41   TRUE
6 Saturn  Gas giant           9.449      0.43   TRUE

In [106]:
str(planets_df)

'data.frame':	8 obs. of  5 variables:
 $ name    : Factor w/ 8 levels "Earth","Jupiter",..: 4 8 1 3 2 6 7 5
 $ type    : Factor w/ 2 levels "Gas giant","Terrestrial planet": 2 2 2 2 1 1 1 1
 $ diameter: num  0.382 0.949 1 0.532 11.209 ...
 $ rotation: num  58.64 -243.02 1 1.03 0.41 ...
 $ rings   : logi  FALSE FALSE FALSE FALSE TRUE TRUE ...


In [107]:
planets_df[1,3]

[1] 0.382

In [108]:
# Print out data for Mars (entire fourth row)
planets_df[4, ]

name type               diameter rotation rings
4 Mars Terrestrial planet 0.532    1.03     FALSE

In [110]:
planets_df[rings, ]

name    type      diameter rotation rings
5 Jupiter Gas giant 11.209    0.41    TRUE 
6 Saturn  Gas giant  9.449    0.43    TRUE 
7 Uranus  Gas giant  4.007   -0.72    TRUE 
8 Neptune Gas giant  3.883    0.67    TRUE

In [111]:
subset(planets_df, diameter < 1)

name    type               diameter rotation rings
1 Mercury Terrestrial planet 0.382      58.64  FALSE
2 Venus   Terrestrial planet 0.949    -243.02  FALSE
4 Mars    Terrestrial planet 0.532       1.03  FALSE

In [112]:
v <- c(3, 100, 1)

v[order(v)]

[1]   1   3 100

In [113]:
# Use order() to create positions
positions <- order(planets_df$diameter)

# Use positions to sort planets_df
planets_df[positions, ]

name    type               diameter rotation rings
1 Mercury Terrestrial planet  0.382     58.64  FALSE
4 Mars    Terrestrial planet  0.532      1.03  FALSE
2 Venus   Terrestrial planet  0.949   -243.02  FALSE
3 Earth   Terrestrial planet  1.000      1.00  FALSE
8 Neptune Gas giant           3.883      0.67   TRUE
7 Uranus  Gas giant           4.007     -0.72   TRUE
6 Saturn  Gas giant           9.449      0.43   TRUE
5 Jupiter Gas giant          11.209      0.41   TRUE

# Lists

In [114]:
my_vector <- 1 : 10

my_matrix <- matrix(1:9, ncol = 3)

my_df <- mtcars[1:5,]

In [115]:
my_list <- list(my_vector, my_matrix, my_df)

In [116]:
my_list

[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[2]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[[3]]
                   mpg cyl disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2